source 'https://rubygems.org'
ruby '2.1.3'

gem 'sinatra'
gem 'puma'
gem 'foreman'
gem 'jekyll'
gem 'rack-contrib'
gem 'rspec'
gem 'rack-test'
gem 'rollbar'
gem 'rack-reverse-proxy'
gem 'rack-rewrite'
