version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.8-node
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: |
            gem install bundle
            bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/vendor/bundle
      - run:
          name: Rake
          command: |
            bundle exec rake

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$heroku_api_key@git.heroku.com/$heroku_app_name.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
