version: 2
jobs:
  test:
    docker:
      - circleci/ruby:2.3
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: |
            bundle install
      - run:
          name: Rake
          command: |
            bundle exec install

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$heroku_api_key@git.heroku.com/$heroku_app_name.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
